### ISSUE TITLE
TypeError: Object #<Object> has no method 'listen'

### ISSUE THREAD

**Issue by luismesas** [node-xmpp/node-xmpp-server#103]
Hi all,

I have seen other closed issues referencing that this error already happened in the past:

```
      TypeError: Object #<Object> has no method 'listen'
        at Object.C2SServer (/Users/luismesas/projects/mycomms/katy/node_modules/node-xmpp-server/lib/c2s/server.js:42:14)
        at startServer (/Users/luismesas/projects/mycomms/katy/features/step_definitions/xmpp/server.js:18:20)
        at World.<anonymous> (/Users/luismesas/projects/mycomms/katy/features/step_definitions/xmpp/server.js:5:3)
        at Object.module.exports.reset (/Users/luismesas/projects/mycomms/katy/features/support/world.js:9:12)
        at World.<anonymous> (/Users/luismesas/projects/mycomms/katy/features/support/hooks.js:7:9)
        at process._tickDomainCallback (node.js:492:13)
        at Function.Module.runMain (module.js:499:11)
        at startup (node.js:119:16)
```

This is the code that raises it:

```
var xmpp = require("node-xmpp-server");
var server = xmpp.C2SServer(xmppServerOpts);
```

I have check with server versions alpha10 & alpha11

**Comment by chris-rock** [comment]
The latest version has listen method: https://github.com/node-xmpp/node-xmpp-server/blob/master/lib/c2s/server.js#L63

Which version are you using?

**Comment by luismesas** [comment]
solved, problem was with this line

```
var server = xmpp.C2SServer(xmppServerOpts);
```

must be
```
var server = new xmpp.C2SServer(xmppServerOpts);
```
