### ISSUE TITLE
Registeration Error

### ISSUE THREAD

**Issue by qnimate** [node-xmpp/node-xmpp-server#114]
Server error when client tries to register a new username and password.

```
TypeError: Cannot call method 'indexOf' of undefined
    at DOMElement.Element.getName (/Users/narayanprusty/Desktop/node-xmpp-server/node_modules/node-xmpp-core/node_modules/ltx/lib/element.js:28:19)
    at DOMElement.Object.defineProperty.get (/Users/narayanprusty/Desktop/node-xmpp-server/node_modules/node-xmpp-core/node_modules/ltx/lib/dom-element.js:22:21)
    at new DOMElement (/Users/narayanprusty/Desktop/node-xmpp-server/node_modules/node-xmpp-core/node_modules/ltx/lib/dom-element.js:10:25)
    at DOMElement._getElement (/Users/narayanprusty/Desktop/node-xmpp-server/node_modules/node-xmpp-core/node_modules/ltx/lib/dom-element.js:16:19)
    at DOMElement.Element.c (/Users/narayanprusty/Desktop/node-xmpp-server/node_modules/node-xmpp-core/node_modules/ltx/lib/element.js:235:28)
    at /Users/narayanprusty/Desktop/node-xmpp-server/lib/c2s/stream.js:281:26
    at C2SStream.<anonymous> (/Users/narayanprusty/Desktop/node-xmpp-server/test/bosh.js:29:13)
    at C2SStream.emit (events.js:98:17)
    at C2SStream.onRegistration (/Users/narayanprusty/Desktop/node-xmpp-server/lib/c2s/stream.js:264:14)
    at C2SStream.onStanza (/Users/narayanprusty/Desktop/node-xmpp-server/lib/c2s/stream.js:156:14)
```

**Comment by qnimate** [comment]
I get this error for this register code

```

        client.on('register', function (opts, cb) {
            cb(new Error('register not supported'))
        })
```

**Comment by sonnyp** [comment]
@qnimate you need to return an object with a XMPP error code and type

for example 
cb({code: 'foo', type: 'bar'})

**Comment by qnimate** [comment]
@sonnyp ohhhh...thanks :)

**Comment by mariansurdu112** [comment]
How to do this?What do you want to say?

**Comment by mariansurdu112** [comment]
@sonnyp  I've follow your advice but i have the same error
